FROM nginx

# 1. Clean out default placeholder assets
RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /etc/nginx/conf.d/default.conf

# 2. Overwrite default virtual server parameters 
COPY expense.conf /etc/nginx/conf.d/default.conf

# 3. Copy your project code files based on your layout
COPY code/static/index.html /usr/share/nginx/html/index.html
COPY code/static/css/ /usr/share/nginx/html/code/static/css/
COPY code/static/js/ /usr/share/nginx/html/code/static/js/
COPY code/static/media/ /usr/share/nginx/html/code/static/media/

# 4. Enforce solid read permissions
RUN chmod -R 755 /usr/share/nginx/html
