version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseAPP@1
      MYSQL_DATABASE: expenses_db
      MYSQL_USER: expense
      MYSQL_PASSWORD: ExpenseAPP@1
    ports:
      - "3306:3306"
    networks:
      - expense-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pExpenseAPP@1"]
      timeout: 5s
      retries: 5
      interval: 5s

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: expense
      DB_PWD: ExpenseAPP@1
      DB_DATABASE: expenses_db
    networks:
      - expense-network  
    depends_on:
      mysql:
        condition: service_healthy

networks:
  expense-network:      
    driver: bridge
