FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseAPP@1 \
    MYSQL_USER=expense \
    MYSQL_PASSWORD=ExpenseAPP@1 \
    MYSQL_DATABASE=transacations 
COPY scripts/*.sql /docker-entrypoint-initdb.d/
#COPY scripts/init.sql /docker-entrypoint-initdb.d/